.TH exfatlabel 8
.SH NAME
exfatlabel \- Get or Set volume label of an exFAT filesystem
.SH SYNOPSIS
.B exfatlabel
[
.B \-v
]
.I device
[
.I label_string
]
.br
.B exfatlabel \-V
.SH DESCRIPTION
.B exfatlabel
Print or set volume label of an existing exFAT filesystem.

If there is a
.I label_string
in argument of exfatlabel, It will be written to volume label
field on given device. If not, exfatlabel will just print out
after reading volume label field from given device.
.PP
.SH OPTIONS
.TP
.B \-V
Prints the version number and exits.
