.TH fsck.exfat 8
.SH NAME
fsck.exfat \- check an exFAT filesystem
.SH SYNOPSIS
.B fsck.exfat
[
.B \-a
] [
.B \-n
] [
.B \-r
] [
.B \-v
] [
.B \-y
] [
.B \-v
]
.I device
.br
.B fsck.exfat \-V
.SH DESCRIPTION
.B fsck.exfat
checks an exFAT filesystem and repairs the filesystem
depending on the options passed.
.PP
.SH OPTIONS
.TP
.BI \-a
This  option  does  the same thing as the -p option.  It is provided for backwards compatibility only;  it  is  suggested  that people use -p option whenever possible.
.TP
.BI \-n
Check the filesystem but do not attempt to repair the filesystem.
.TP
.BI \-p
Repair the filesystem without user interaction if it can be done safely.
.TP
.BI \-r
Repair the filesystem interactively.
.TP
.BI \-v
Prints verbose debugging information while checking the exFAT filesystem.
.TP
.BI \-V
Prints the version number and exits.
.TP
.B \-y
Repair the filesystem answering yes to all questions.
.SH SEE ALSO
.BR fsck (8),
.BR fstab (5),
