dist: bionic

language: c

notifications:
 - email: true

before_script:
 - sudo apt-get install linux-headers-$(uname -r)
 - sudo apt-get install xz-utils
 - git clone --branch=exfat-next https://github.com/namjaejeon/exfat_oot
 - ./.travis_get_mainline_kernel
 - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
 - export PATH=/usr/local/lib:$PATH

script:
 # run checkpatch.pl
 - git format-patch -20
 - ./linux/scripts/checkpatch.pl *.patch || true
 # build & install exfatprogs
 - ./autogen.sh > /dev/null
 - ./configure > /dev/null
 - make -j$((`nproc`+1)) > /dev/null
 - sudo make install > /dev/null
 # build & install exfat
 - cd exfat_oot
 - make > /dev/null
 - sudo make install > /dev/null
 - sudo modprobe exfat
 - sudo mkdir -p /mnt/test
 - cd ..
 # run fsck repair testcases
 - cd tests
 - sudo ./test_fsck.sh
 # create file/director test
 - truncate -s 10G test.img
 - sudo losetup /dev/loop22 test.img
 - sudo mkfs.exfat /dev/loop22
 - sudo mount -t exfat /dev/loop22 /mnt/test/
 - cd /mnt/test/
 - i=1;while [ $i -le 10000 ];do sudo touch file$i;if [ $? != 0 ]; then exit 1; fi; i=$(($i + 1));done
 - sync
 - sudo rm -rf *
 - i=1;while [ $i -le 10000 ];do sudo mkdir dir$i;if [ $? != 0 ]; then exit 1; fi; i=$(($i + 1));done
 - sync
 - sudo rm -rf *
 - i=1;while [ $i -le 10000 ];do sudo touch file$i;if [ $? != 0 ]; then exit 1; fi; i=$(($i + 1));done
 - i=1;while [ $i -le 10000 ];do sudo mkdir dir$i;if [ $? != 0 ]; then exit 1; fi; i=$(($i + 1));done
 - sync
 - sudo fsck.exfat /dev/loop22
 - sudo find . -delete
 - sudo fsck.exfat /dev/loop22
 - cd -
